export default {
  index: 'Overview',
  supervisor: 'Supervisor',
  triage: 'Triage',
  heal: 'Heal',
  generate: 'Generate',
  plan: 'Plan',
  scenario: 'Scenario',
  report: 'Report',
  validate: 'Validate',
  auth: 'Auth',
  review: 'Review',
  a11y: 'a11y',
  'ado-a11y': 'ado-a11y',
};
